#!/bin/bash

USER_ID=$( id -u )
GROUP_ID=$( id -g )

docker build \
       -f Dockerfile.ubuntu             \
       --build-arg USER_ID=${USER_ID}   \
       --build-arg GROUP_ID=${GROUP_ID} \
       -t devshell                      \
       .
